[package]
name = "helper"
version = "0.1.0"
edition = "2021"

[dependencies]
genanki-rs = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.4", features = ["derive"] }
glob = "0.3.1"
anyhow = "1.0.86"
rand = "0.8.5"